import { Achievement } from '@/types';

export const ACHIEVEMENTS: Achievement[] = [
  // Water Achievements
  {
    id: 'water-bronze-1',
    name: 'Peixinho Fora D\'Água',
    description: 'Complete 7 metas de hidratação',
    category: 'water',
    tier: 'bronze',
    icon: 'Droplets',
    criteria: '7 metas de água',
    progress: 0,
    maxProgress: 7,
    unlocked: false,
  },
  {
    id: 'water-silver-1',
    name: 'Guardião das Marés',
    description: 'Complete 30 metas de hidratação',
    category: 'water',
    tier: 'silver',
    icon: 'Waves',
    criteria: '30 metas de água',
    progress: 0,
    maxProgress: 30,
    unlocked: false,
  },
  {
    id: 'water-gold-1',
    name: 'Último Dobrador de Água',
    description: 'Complete 100 metas de hidratação',
    category: 'water',
    tier: 'gold',
    icon: 'Zap',
    criteria: '100 metas de água',
    progress: 0,
    maxProgress: 100,
    unlocked: false,
  },
  
  // Workout Achievements
  {
    id: 'workout-bronze-1',
    name: 'Iniciante Imparável',
    description: 'Complete 10 treinos',
    category: 'workout',
    tier: 'bronze',
    icon: 'Flame',
    criteria: '10 treinos',
    progress: 0,
    maxProgress: 10,
    unlocked: false,
  },
  {
    id: 'workout-silver-1',
    name: 'Gladiador da Segunda',
    description: 'Treine 5 segundas-feiras',
    category: 'workout',
    tier: 'silver',
    icon: 'Sword',
    criteria: '5 segundas-feiras',
    progress: 0,
    maxProgress: 5,
    unlocked: false,
  },
  {
    id: 'workout-gold-1',
    name: 'Monstro da Sexta',
    description: 'Treine 5 sextas-feiras',
    category: 'workout',
    tier: 'gold',
    icon: 'Trophy',
    criteria: '5 sextas-feiras',
    progress: 0,
    maxProgress: 5,
    unlocked: false,
  },
  
  // Social Achievements
  {
    id: 'social-bronze-1',
    name: 'Inspirador',
    description: 'Receba 50 curtidas no feed',
    category: 'social',
    tier: 'bronze',
    icon: 'Heart',
    criteria: '50 curtidas',
    progress: 0,
    maxProgress: 50,
    unlocked: false,
  },
  {
    id: 'social-silver-1',
    name: 'Lenda do Feed',
    description: 'Receba 200 curtidas no feed',
    category: 'social',
    tier: 'silver',
    icon: 'Star',
    criteria: '200 curtidas',
    progress: 0,
    maxProgress: 200,
    unlocked: false,
  },
  {
    id: 'social-gold-1',
    name: 'Ícone da Competição',
    description: 'Receba 500 curtidas no feed',
    category: 'social',
    tier: 'gold',
    icon: 'Crown',
    criteria: '500 curtidas',
    progress: 0,
    maxProgress: 500,
    unlocked: false,
  },
  
  // Event Achievements
  {
    id: 'event-bronze-1',
    name: 'Participante Ativo',
    description: 'Participe de 3 eventos',
    category: 'event',
    tier: 'bronze',
    icon: 'Calendar',
    criteria: '3 eventos',
    progress: 0,
    maxProgress: 3,
    unlocked: false,
  },
  {
    id: 'event-silver-1',
    name: 'Competidor',
    description: 'Participe de 10 eventos',
    category: 'event',
    tier: 'silver',
    icon: 'CalendarClock',
    criteria: '10 eventos',
    progress: 0,
    maxProgress: 10,
    unlocked: false,
  },
  {
    id: 'event-gold-1',
    name: 'Campeão',
    description: 'Vence 5 eventos',
    category: 'event',
    tier: 'gold',
    icon: 'Medal',
    criteria: '5 vitórias',
    progress: 0,
    maxProgress: 5,
    unlocked: false,
  },
];
